version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/adf-apps/"
    schedule:
      interval: "weekly"
    groups:
      docker:
        patterns:
          - "*"
