name: aps-deployment
description: Clone aps-deployment sources
runs:
  using: "composite"
  steps:
      - name: Checkout acs-deployment sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: Alfresco/alfresco-process-services-deployment
          ref: v2.1.1
          path: aps-deployment
