name: aps-deployment
description: Clone aps-deployment sources
inputs:
  token:
    description: "The github token"
    required: true
runs:
  using: "composite"
  steps:
      - name: Checkout aps-deployment sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: Alfresco/alfresco-process-services-deployment
          ref: v3.3.0
          token: ${{ inputs.token }}
          path: aps-deployment
