name: aps-deployment
description: Clone aps-deployment sources
inputs:
  token:
    description: "The github token"
    required: true
runs:
  using: "composite"
  steps:
      - name: Checkout acs-deployment sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: Alfresco/alfresco-process-services-deployment
          ref: v3.1.0
          token: ${{ inputs.token }}
          path: aps-deployment
