name: helm-prepare
description: Prepare for helm installation
inputs:
  ingress-nginx-ref:
    description: "The ingress-nginx controller reference"
    required: false
    default: "controller-v1.8.2"
  metrics:
    description: "Enable metrics for ingress-nginx"
    required: false
    default: "true"
  helm-version:
    description: "The helm version to use"
    required: false
    default: "3.15.2"
  docker-username:
    description: "Docker Hub username"
    required: true
  docker-password:
    description: "Docker Hub password"
    required: true
  quay-username:
    description: "Quay.io username"
    required: true
  quay-password:
    description: "Quay.io password"
    required: true
  github-registry:
    description: "GitHub Container Registry URL"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true
  github-actor:
    description: "GitHub actor for authentication"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup cluster
      uses: Alfresco/alfresco-build-tools/.github/actions/setup-kind@v12.10.3
      with:
        ingress-nginx-ref: ${{ inputs.ingress-nginx-ref }}
        metrics: ${{ inputs.metrics }}

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      with:
        version: ${{ inputs.helm-version }}

    - name: Login to Docker Hub
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9  # v3.7.0
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Login to Quay.io
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9  # v3.7.0
      with:
        registry: quay.io
        username: ${{ inputs.quay-username }}
        password: ${{ inputs.quay-password }}

    - name: Log in to the Container registry
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ${{ inputs.github-registry }}
        username: ${{ inputs.github-actor }}
        password: ${{ inputs.github-token }}

    - name: Create registries auth secret
      shell: bash
      run: >-
        kubectl create secret generic regcred
        --from-file=.dockerconfigjson=$HOME/.docker/config.json
        --type=kubernetes.io/dockerconfigjson
