name: helm-prepare
description: Prepare for helm installation
inputs:
  ingress-nginx-ref:
    description: "The ingress-nginx controller reference"
    required: false
    default: "controller-v1.8.2"
  metrics:
    description: "Enable metrics for ingress-nginx"
    required: false
    default: "true"
  helm-version:
    description: "The helm version to use"
    required: false
    default: "3.15.2"
  docker-username:
    description: "Docker Hub username"
    required: true
  docker-password:
    description: "Docker Hub password"
    required: true
  quay-username:
    description: "Quay.io username"
    required: true
  quay-password:
    description: "Quay.io password"
    required: true
  github-registry:
    description: "GitHub Container Registry URL"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true
  github-actor:
    description: "GitHub actor for authentication"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup cluster
      uses: Alfresco/alfresco-build-tools/.github/actions/setup-kind@v8.30.0
      with:
        ingress-nginx-ref: ${{ inputs.ingress-nginx-ref }}
        metrics: ${{ inputs.metrics }}

    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
      with:
        version: ${{ inputs.helm-version }}

    - name: Login to Docker Hub
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1  # v3.5.0
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Login to Quay.io
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1  # v3.5.0
      with:
        registry: quay.io
        username: ${{ inputs.quay-username }}
        password: ${{ inputs.quay-password }}

    - name: Log in to the Container registry
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
      with:
        registry: ${{ inputs.github-registry }}
        username: ${{ inputs.github-actor }}
        password: ${{ inputs.github-token }}

    - name: Create registries auth secret
      shell: bash
      run: >-
        kubectl create secret generic regcred
        --from-file=.dockerconfigjson=$HOME/.docker/config.json
        --type=kubernetes.io/dockerconfigjson
