#!/bin/bash

if [ -f "$ACTIVITI_APP_PROPS" ] && [ -s "$ACTIVITI_APP_PROPS" ]; then
    echo "Activiti app properties file already exists at $ACTIVITI_APP_PROPS - using mounted configuration"
else
    echo "Generating activiti app properties file using environment variables and defaults"

    export ACTIVITI_LICENSE_MULTI_TENANT="${ACTIVITI_LICENSE_MULTI_TENANT:-false}"
    export ACTIVITI_DATASOURCE_URL="${ACTIVITI_DATASOURCE_URL:-jdbc:h2:mem:db1;DB_CLOSE_DELAY=1000}"
    export ACTIVITI_DATASOURCE_DRIVER="${ACTIVITI_DATASOURCE_DRIVER:-org.h2.Driver}"
    export ACTIVITI_DATASOURCE_USERNAME="${ACTIVITI_DATASOURCE_USERNAME:-alfresco}"
    export ACTIVITI_DATASOURCE_PASSWORD="${ACTIVITI_DATASOURCE_PASSWORD:-alfresco}"
    export ACTIVITI_HIBERNATE_DIALECT="${ACTIVITI_HIBERNATE_DIALECT:-org.hibernate.dialect.H2Dialect}"

    export ACTIVITI_ADMIN_EMAIL="${ACTIVITI_ADMIN_EMAIL:-admin@app.activiti.com}"
    export ACTIVITI_ADMIN_PASSWORD_HASH="${ACTIVITI_ADMIN_PASSWORD_HASH:-25a463679c56c474f20d8f592e899ef4cb3f79177c19e3782ed827b5c0135c466256f1e7b60e576e}"

    export ACTIVITI_ES_SERVER_TYPE="${ACTIVITI_ES_SERVER_TYPE:-none}"
    export ACTIVITI_ES_REST_CLIENT_ADDRESS="${ACTIVITI_ES_REST_CLIENT_ADDRESS:-localhost}"
    export ACTIVITI_ES_REST_CLIENT_PORT="${ACTIVITI_ES_REST_CLIENT_PORT:-9200}"
    export ACTIVITI_ES_REST_CLIENT_SCHEMA="${ACTIVITI_ES_REST_CLIENT_SCHEMA:-http}"
    export ACTIVITI_ES_REST_CLIENT_AUTH_ENABLED="${ACTIVITI_ES_REST_CLIENT_AUTH_ENABLED:-false}"
    export ACTIVITI_ES_REST_CLIENT_USERNAME="${ACTIVITI_ES_REST_CLIENT_USERNAME:-admin}"
    export ACTIVITI_ES_REST_CLIENT_PASSWORD="${ACTIVITI_ES_REST_CLIENT_PASSWORD:-esadmin}"
    export ACTIVITI_ES_REST_CLIENT_KEYSTORE="${ACTIVITI_ES_REST_CLIENT_KEYSTORE:-}"
    export ACTIVITI_ES_REST_CLIENT_KEYSTORE_TYPE="${ACTIVITI_ES_REST_CLIENT_KEYSTORE_TYPE:-jks}"
    export ACTIVITI_ES_REST_CLIENT_KEYSTORE_PASSWORD="${ACTIVITI_ES_REST_CLIENT_KEYSTORE_PASSWORD:-}"

    export ACTIVITI_CORS_ENABLED="${ACTIVITI_CORS_ENABLED:-true}"
    export ACTIVITI_CORS_ALLOWED_ORIGINS="${ACTIVITI_CORS_ALLOWED_ORIGINS:-}"
    export ACTIVITI_CORS_ALLOWED_ORIGIN_PATTERNS="${ACTIVITI_CORS_ALLOWED_ORIGIN_PATTERNS:-*}"
    export ACTIVITI_CORS_ALLOWED_METHODS="${ACTIVITI_CORS_ALLOWED_METHODS:-GET,POST,HEAD,OPTIONS,PUT,DELETE}"
    export ACTIVITI_CORS_ALLOWED_HEADERS="${ACTIVITI_CORS_ALLOWED_HEADERS:-Authorization,Content-Type,Cache-Control,X-Requested-With,accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,X-CSRF-Token}"

    export ACTIVITI_CSRF_DISABLED="${ACTIVITI_CSRF_DISABLED:-false}"
    export ACTIVITI_REVIEW_WORKFLOWS_ENABLED="${ACTIVITI_REVIEW_WORKFLOWS_ENABLED:-}"

    # Process template with envsubst
    if [ -f "$ACTIVITI_APP_PROPS_TEMPLATE" ]; then
        echo "Processing template: $ACTIVITI_APP_PROPS_TEMPLATE -> $ACTIVITI_APP_PROPS"
        envsubst < "$ACTIVITI_APP_PROPS_TEMPLATE" > "$ACTIVITI_APP_PROPS"
        echo "Activiti app properties file generated successfully"
    else
        echo "ERROR: Template file not found: $ACTIVITI_APP_PROPS_TEMPLATE"
        exit 1
    fi
fi

if [ -f "$ACTIVITI_IDENTITY_SERVICE_PROPS" ] && [ -s "$ACTIVITI_IDENTITY_SERVICE_PROPS" ]; then
    echo "Identity service properties file already exists at $ACTIVITI_IDENTITY_SERVICE_PROPS - using mounted configuration"
else
    echo "Generating identity service properties file using environment variables and defaults"

    # Set defaults and export for envsubst
    export IDENTITY_SERVICE_ENABLED="${IDENTITY_SERVICE_ENABLED:-false}"
    export IDENTITY_SERVICE_REALM="${IDENTITY_SERVICE_REALM:-alfresco}"
    export IDENTITY_SERVICE_AUTH="${IDENTITY_SERVICE_AUTH:-http://localhost:8180/auth}"
    export IDENTITY_SERVICE_RESOURCE="${IDENTITY_SERVICE_RESOURCE:-alfresco}"
    export IDENTITY_SERVICE_PRINCIPAL_ATTRIBUTE="${IDENTITY_SERVICE_PRINCIPAL_ATTRIBUTE:-email}"
    export IDENTITY_CREDENTIALS_SECRET="${IDENTITY_CREDENTIALS_SECRET:-}"

    export IDENTITY_SERVICE_USE_BROWSER_BASED_LOGOUT="${IDENTITY_SERVICE_USE_BROWSER_BASED_LOGOUT:-false}"

    export IDENTITY_SERVICE_CONTENT_SSO_ENABLED="${IDENTITY_SERVICE_CONTENT_SSO_ENABLED:-${IDENTITY_SERVICE_ENABLED}}"
    export IDENTITY_SERVICE_CONTENT_SSO_CLIENT_ID="${IDENTITY_SERVICE_CONTENT_SSO_CLIENT_ID:-${IDENTITY_SERVICE_RESOURCE}}"
    export IDENTITY_SERVICE_CONTENT_SSO_CLIENT_SECRET="${IDENTITY_SERVICE_CONTENT_SSO_CLIENT_SECRET:-${IDENTITY_CREDENTIALS_SECRET}}"
    export IDENTITY_SERVICE_CONTENT_SSO_REALM="${IDENTITY_SERVICE_CONTENT_SSO_REALM:-${IDENTITY_SERVICE_REALM}}"
    export IDENTITY_SERVICE_CONTENT_SSO_SCOPE="${IDENTITY_SERVICE_CONTENT_SSO_SCOPE:-offline_access}"
    export IDENTITY_SERVICE_CONTENT_SSO_AUTH_URI="${IDENTITY_SERVICE_CONTENT_SSO_AUTH_URI:-${IDENTITY_SERVICE_AUTH}/realms/${IDENTITY_SERVICE_CONTENT_SSO_REALM}/protocol/openid-connect/auth}"
    export IDENTITY_SERVICE_CONTENT_SSO_TOKEN_URI="${IDENTITY_SERVICE_CONTENT_SSO_TOKEN_URI:-${IDENTITY_SERVICE_AUTH}/realms/${IDENTITY_SERVICE_CONTENT_SSO_REALM}/protocol/openid-connect/token}"
    export IDENTITY_SERVICE_CONTENT_SSO_REDIRECT_URI="${IDENTITY_SERVICE_CONTENT_SSO_REDIRECT_URI:-http://localhost:9999/activiti-app/app/rest/integration/sso/confirm-auth-request}"

    export IDENTITY_SERVICE_RETRY_MAXATTEMPTS="${IDENTITY_SERVICE_RETRY_MAXATTEMPTS:-20}"
    export IDENTITY_SERVICE_RETRY_DELAY="${IDENTITY_SERVICE_RETRY_DELAY:-10000}"

    # Process template with envsubst
    if [ -f "$ACTIVITI_IDENTITY_SERVICE_PROPS_TEMPLATE" ]; then
        echo "Processing template: $ACTIVITI_IDENTITY_SERVICE_PROPS_TEMPLATE -> $ACTIVITI_IDENTITY_SERVICE_PROPS"
        envsubst < "$ACTIVITI_IDENTITY_SERVICE_PROPS_TEMPLATE" > "$ACTIVITI_IDENTITY_SERVICE_PROPS"
        echo "Identity service properties file generated successfully"
    else
        echo "ERROR: Template file not found: $ACTIVITI_IDENTITY_SERVICE_PROPS_TEMPLATE"
        exit 1
    fi
fi

exec catalina.sh run "$@"
