name: acs-deployment
description: Clone acs-deployment sources
runs:
  using: "composite"
  steps:
      - name: Checkout acs-deployment sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: Alfresco/acs-deployment
          ref: 79a4d3c4facc9912a5f3990144488ba0da965dfc # waiting for the next release
          path: acs-deployment
