name: acs-deployment
description: Clone acs-deployment sources
runs:
  using: "composite"
  steps:
      - name: Checkout acs-deployment sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: Alfresco/acs-deployment
          ref: v10.6.0
          path: acs-deployment
