name: acs-deployment
description: Clone acs-deployment sources
runs:
  using: "composite"
  steps:
      - name: Checkout acs-deployment sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: Alfresco/acs-deployment
          ref: ba44e0224bace9ea981e50a762398e77949ee41e # after migrating from bitnami
          path: acs-deployment
