name: acs-deployment
description: Clone acs-deployment sources
runs:
  using: "composite"
  steps:
      - name: Checkout acs-deployment sources
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          repository: Alfresco/acs-deployment
          ref: v10.2.0
          path: acs-deployment
