name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Makefile'
      - '.github/workflows/test-make.yml'
      - '.github/workflows/kics.yml'
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'Makefile'
      - '.github/workflows/test-make.yml'
      - '.github/workflows/kics.yml'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  # telemetry
  actions: read
  # ghcr push
  packages: write
  attestations: write
  id-token: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: '! github.event.pull_request.head.repo.fork'
    permissions:
      contents: write
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v8.22.1
        with:
          auto-commit: "true"
  CI:
    name: Build ACS v${{ matrix.acs_version }}${{ matrix.aps_version && format(' and APS v{0}', matrix.aps_version) || '' }}
    needs: pre-commit
    uses: ./.github/workflows/reusable_build_and_test.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - acs_version: 25
            aps_version: 25
          - acs_version: 23
            aps_version: 24
          - acs_version: 74
            aps_version: ''
          - acs_version: 73
            aps_version: ''
    with:
      tag: ${{ github.event_name == 'pull_request' && format('pr-{0}-v{1}', github.event.pull_request.number, matrix.acs_version) || format('{0}-v{1}', github.ref_name, matrix.acs_version) }}
      acs_version: ${{ matrix.acs_version }}
      aps_version: ${{ matrix.aps_version }}
    secrets: inherit
