name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Makefile'
      - '.github/workflows/test-make.yml'
      - '.github/workflows/kics.yml'
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'Makefile'
      - '.github/workflows/test-make.yml'
      - '.github/workflows/kics.yml'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: '! github.event.pull_request.head.repo.fork'
    permissions:
      contents: write
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v8.2.0
        with:
          auto-commit: "true"
  CI:
    needs: pre-commit
    uses: ./.github/workflows/reusuable_build_and_test.yml
    strategy:
      fail-fast: false
      matrix:
        version: [23, 74]
    with:
      registry: ghcr.io
      registry_namespace: alfresco
      tag: ${{ github.event_name == 'pull_request' && format('pr-{0}-v{1}', github.event.pull_request.number, matrix.version) || format('{0}-v{1}', github.ref_name, matrix.version) }}
      acs_deployment_version: 78132d95e29d7126025e127740d10cf958164947 # 8.6.0-alpha.0 with compose healthcheck
      acs_version: ${{ matrix.version }}
    secrets: inherit
