name: Build, Run and Test Docker Image

on: [push]

jobs:
  build-run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
          - artifact: alfresco-elasticsearch-live-indexing-metadata
            version: 4.0.1
            name: alfresco-enterprise-search-metadata
            path: search/enterprise/metadata
            extension: -app.jar
            group: org.alfresco

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
    
      - name: Setup .netrc
        run: |
          echo "machine nexus.alfresco.com" >> ~/.netrc
          echo "login ${{ secrets.NEXUS_USERNAME }}" >> ~/.netrc
          echo "password ${{ secrets.NEXUS_PASSWORD }}" >> ~/.netrc

      - name: Fetch artifacts from nexus 
        run: bash ${{ github.workspace }}/scripts/fetch-artifact.sh ${{ matrix.images.artifact }} ${{ matrix.images.version }} ${{ matrix.images.extension }} ${{ matrix.images.group }} ${{ matrix.images.path }}
        working-directory: ${{ github.workspace }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
            context: .
            tags: ${{ matrix.images.name }}:test
            push: false
            load: true
            file: ${{ github.workspace }}/${{ matrix.images.path }}/Dockerfile
      
      - name: Run Docker image
        run: docker run -d -p 8080:8080 ${{ matrix.images.name }}:test

      - name: Wait for container
        run: sleep 30s

      - uses: Alfresco/alfresco-build-tools/.github/actions/docker-dump-containers-logs@v5.33.0

      - name: Save Docker image
        run: docker save ${{ matrix.images.name }}:test -o /tmp/${{ matrix.images.name }}.tar

      - name: Upload image as a tar for next job
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: /tmp/${{ matrix.images.name }}.tar

  compose:
    name: docker-compose
    needs: build-run-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: images
          path: /tmp
      
      - name: Load Docker images
        run: |
          ls -1 /tmp/*.tar | xargs --no-run-if-empty -L 1 docker load -i
          docker image ls -a

      - name: Verify docker-compose
        uses: Alfresco/alfresco-build-tools/.github/actions/dbp-charts/verify-compose@OPSEXP-2732-compose
        timeout-minutes: 10
        with:
          compose_pull: false
          compose_file_path: docker-compose.yml
          quay_username: ${{ secrets.QUAY_USERNAME }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}

      - uses: Alfresco/alfresco-build-tools/.github/actions/docker-dump-containers-logs@v5.33.0
