name: Build, Run and Test Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v6.0.0
        with:
          auto-commit: "true"

  build-test:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup nexus authentication
        run: |
          echo "machine nexus.alfresco.com" >> ~/.netrc
          echo "login ${{ secrets.NEXUS_USERNAME }}" >> ~/.netrc
          echo "password ${{ secrets.NEXUS_PASSWORD }}" >> ~/.netrc

      - name: Fetch artifacts from nexus
        run: ./scripts/fetch-artifact.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Login to Quay.io
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - name: Bake Docker images
        uses: docker/bake-action@a4d7f0b5b91c14a296d792d4ec53a9db17f02e67  # v5.5.0
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Show all built images
        run: docker images

      - name: Docker save all baked images whose name include `alfresco`
        run: |
          docker save -o /tmp/alfresco-docker-images.tar $(docker images --format "{{.Repository}}:{{.Tag}}" | grep alfresco)

      - name: Upload images as artifact
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: docker-images
          path: /tmp/alfresco-docker-images.tar
          retention-days: 1
          compression-level: 0

  compose-test:
    if: false
    name: compose-test ${{ matrix.docker-compose-file }}
    needs: build-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-compose-file: [docker-compose.yml, docker-compose-components.yml]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db  # v3.6.1
    
      - name: Download artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: /tmp
          name: docker-images

      - name: Load Docker images
        run: |
          ls -1 /tmp/*.tar | xargs --no-run-if-empty -L 1 docker load -i
          docker image ls -a

      - name: Verify docker-compose
        uses: Alfresco/alfresco-build-tools/.github/actions/dbp-charts/verify-compose@v6.0.0
        timeout-minutes: 10
        with:
          compose_pull: false
          compose_file_path: docker-compose/${{ matrix.docker-compose-file }}
          quay_username: ${{ secrets.QUAY_USERNAME }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}

      - uses: Alfresco/alfresco-build-tools/.github/actions/docker-dump-containers-logs@v6.0.0

  helm-test:
    name: helm test
    needs: build-test
    runs-on: alfrescoPub-ubuntu2204-16G-4CPU
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: /tmp
          name: docker-images

      - name: Setup cluster
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-kind@v5.35.0
        with:
          ingress-nginx-ref: controller-v1.8.2
          metrics: "true"

      - name: Load Docker images
        run: |
          kind get clusters
          ls -1 /tmp/*.tar | xargs --no-run-if-empty -L 1 kind load image-archive -n chart-testing

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814
        with:
          version: "3.14.3"

      - name: Login to Quay.io
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20  # v3.1.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Create registries auth secret
        run: >-
          kubectl create secret generic regcred
          --from-file=.dockerconfigjson=$HOME/.docker/config.json
          --type=kubernetes.io/dockerconfigjson

      - name: Fetch upstream values for tests
        run: >-
          curl -L
          https://raw.githubusercontent.com/Alfresco/acs-deployment/c1096488a9dd2bef4fe20f9677a14afba4fc8932/test/enterprise-integration-test-values.yaml
          -o test/helm/enterprise-integration-test-values.yaml &&
          ls -l test/helm/enterprise-integration-test-values.yaml

      - name: Helm install
        run: |
          helm repo add alfresco https://kubernetes-charts.alfresco.com/stable
          helm repo update
          helm install acs alfresco/alfresco-content-services \
            --set global.search.sharedSecret="$(openssl rand -hex 24)" \
            --set global.known_urls=http://localhost \
            --set global.alfrescoRegistryPullSecrets=regcred \
            --values test/helm/enterprise-integration-test-values.yaml \
            --values test/helm/test-overrides.yaml

      - name: Watch Helm deployment
        run: |
          kubectl get pods --watch &
          KWPID=$!
          kubectl wait --timeout=7m --all=true --for=condition=Available deploy && kill $KWPID
          echo -n "Waiting for ESC Reindexing job to complete... "
          kubectl wait --timeout=5m --for=condition=complete job/acs-alfresco-search-enterprise-reindexing
          echo "Completed."

      - name: Spit cluster status after install
        if: always()
        run: |
          helm ls --all-namespaces --all
          helm status acs --show-resources
          kubectl describe pod

      - name: Run helm test
        id: helm_test
        run: helm test acs

      - name: Spit cluster status after helm test
        if: always() && steps.helm_test.outcome != 'skipped'
        run: |
          kubectl logs -l app.kubernetes.io/component=dtas --tail=-1
          kubectl get all --all-namespaces
          kubectl describe pod
          kubectl logs -l app.kubernetes.io/name=mediation --tail=-1
