name: Cleanup Docker images on ghcr.io

on:
  pull_request:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      
      - name: Extract all image names from HCL
        id: extract_image_names
        run: |
          image_names=$(grep 'tags' docker-bake.hcl | sed -n 's/.*\/\([^:]*\):.*/\1/p' | tr '\n' ',' | sed 's/,$//')
          echo "IMAGE_NAMES=$image_names" >> $GITHUB_ENV

      - name: Display the list of image names
        run: |
          echo "Extracted image names are: ${{ env.IMAGE_NAMES }}"
