name: Cleanup Docker images on ghcr.io

on:
  pull_request:
    branches:
      - main

permissions:
  packages: write

env:
  PACKAGE_NAMES: |
    alfresco-transform-router

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Remove tag ${{format('pr-{0}', github.event.pull_request.number)}}
        uses: dataaxiom/ghcr-cleanup-action@98b4022383d6ddb70ccbf6a378b4d8c67a60f066
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          owner: Alfresco
          repository: alfresco-dockerfiles-bakery
          packages: ${{ env.PACKAGE_NAMES }}
          delete-tags: ${{format('pr-{0}', github.event.pull_request.number)}}
          dry-run: true
