name: Cleanup Docker images on ghcr.io

on:
  pull_request:
    branches:
      - main

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Remove tag ${{format('pr-{0}', github.event.pull_request.number)}}
        uses: dataaxiom/ghcr-cleanup-action@98b4022383d6ddb70ccbf6a378b4d8c67a60f066
        with:
          token: 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
          owner: Alfresco
          repository: alfresco-dockerfiles-bakery
          dry-run: true
