name: Compose Test

on:
  workflow_call:
    inputs:
      ARTIFACT_NAME:
        required: true
        type: string
    secrets:
      QUAY_PASSWORD:
        required: true
      QUAY_USERNAME:
        required: true

jobs:
  compose-test:
    name: compose-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db  # v3.6.1

      - name: Download artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: /tmp
          name: ${{ inputs.ARTIFACT_NAME }}

      - name: Load Docker images
        run: |
          docker load -i /tmp/${{ inputs.ARTIFACT_NAME }}.tar
          docker image ls -a

      - name: Verify docker-compose
        uses: Alfresco/alfresco-build-tools/.github/actions/dbp-charts/verify-compose@v6.0.1
        timeout-minutes: 10
        with:
          compose_pull: false
          compose_file_path: test/docker-compose.yml
          quay_username: ${{ secrets.QUAY_USERNAME }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}

      - uses: Alfresco/alfresco-build-tools/.github/actions/docker-dump-containers-logs@v6.0.0
