name: Compose Test

on:
  workflow_call:
    inputs:
      ARTIFACT_NAME:
        required: true
        type: string
      ACS_VALUES_VERSION:
        required: true
        type: string
      ACS_CHART_VERSION:
        required: true
        type: string
    secrets:
      QUAY_PASSWORD:
        required: true
      QUAY_USERNAME:
        required: true

jobs:
  helm-test:
    name: helm test
    runs-on: alfrescoPub-ubuntu2204-16G-4CPU
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: /tmp
          name: ${{ inputs.ARTIFACT_NAME }}

      - name: Setup cluster
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-kind@v5.35.0
        with:
          ingress-nginx-ref: controller-v1.8.2
          metrics: "true"

      - name: Load Docker images
        run: |
          kind load image-archive -n chart-testing /tmp/${{ inputs.ARTIFACT_NAME }}.tar

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: "3.15.2"

      - name: Login to Quay.io
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20  # v3.1.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Create registries auth secret
        run: >-
          kubectl create secret generic regcred
          --from-file=.dockerconfigjson=$HOME/.docker/config.json
          --type=kubernetes.io/dockerconfigjson

      - name: Fetch upstream values for tests
        run: >-
          curl -ssfL
          https://raw.githubusercontent.com/Alfresco/acs-deployment/${{ inputs.ACS_VALUES_VERSION }}/test/enterprise-integration-test-values.yaml
          -o test/helm/enterprise-integration-test-values.yaml &&
          ls -l test/helm/enterprise-integration-test-values.yaml &&
          cat test/helm/enterprise-integration-test-values.yaml

      - name: Helm install
        id: helm_install
        run: |
          helm repo add alfresco https://kubernetes-charts.alfresco.com/stable
          helm repo update
          helm install acs alfresco/alfresco-content-services \
            --version ${{ inputs.ACS_CHART_VERSION }} \
            --set global.search.sharedSecret="$(openssl rand -hex 24)" \
            --set global.known_urls=http://localhost \
            --set global.alfrescoRegistryPullSecrets=regcred \
            --values test/helm/enterprise-integration-test-values.yaml \
            --values test/helm/test-overrides.yaml

      - name: Watch Helm deployment
        env:
          HELM_INSTALL_TIMEOUT: 8m
        run: |
          kubectl get pods --watch &
          KWPID=$!
          kubectl wait --timeout=${{ env.HELM_INSTALL_TIMEOUT }} --all=true --for=condition=Ready pods
          kill $KWPID
          echo "Waiting for ESC Reindexing job to complete... "
          kubectl wait --timeout=5m --for=condition=complete job/acs-alfresco-search-enterprise-reindexing

      - name: Debug cluster status after install
        if: always() && steps.helm_install.outcome != 'skipped'
        run: |
          helm ls --all-namespaces --all
          kubectl get all --all-namespaces
          kubectl describe pod

      - name: Run helm test
        id: helm_test
        run: helm test acs

      - name: Debug cluster status after helm test
        if: always() && steps.helm_test.outcome != 'skipped'
        run: |
          kubectl logs -l app.kubernetes.io/component=dtas --tail=-1
          kubectl get all --all-namespaces
          kubectl describe pod
