name: kics

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  security-events: write
  contents: write

jobs:
  kics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Run KICS Scan
        uses: checkmarx/kics-github-action@63fca4ca72e56edbb5a599ee756e6af1fdb1e785 # v2.1.18
        with:
          path: './'
          ignore_on_exit: results
          output_path: report-dir/
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          enable_jobs_summary: true
          platform_type: dockerfile
          disable_secrets: true
          output_formats: sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v3.29.5
        with:
          sarif_file: report-dir/results.sarif
